# Generated by Django 4.2.13 on 2024-07-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم')),
                ('persian_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='اسم فارسی')),
                ('country_id', models.CharField(blank=True, max_length=3, null=True, verbose_name='آیدی_کشور')),
                ('continent', models.CharField(blank=True, max_length=13, null=True, verbose_name='قاره')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='جمعیت')),
                ('flag', models.CharField(blank=True, max_length=60, null=True, verbose_name='قاره')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشور ها',
            },
        ),
        migrations.CreateModel(
            name='Vpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم')),
                ('platform', models.CharField(choices=[('Android', 'Android'), ('Telegram', 'Telegram'), ('Windows', 'Windows'), ('Chrome', 'Chrome'), ('Ios', 'Ios')], max_length=10, verbose_name='پلتفرم')),
                ('vpn_maker', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سازنده')),
                ('vpn_normal_user_fee', models.CharField(blank=True, choices=[('Free', 'Free'), ('Limited Free', 'Limited Free'), ('Non-free', 'Non-free')], max_length=12, null=True, verbose_name='وضعیت رایگان بودن')),
                ('vpn_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vpn_country', to='vpn.country', verbose_name='کشور سازنده')),
            ],
            options={
                'verbose_name': 'فیلتر شکن',
                'verbose_name_plural': 'فیلتر شکن ها',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(verbose_name='تاریخ')),
                ('time', models.CharField(max_length=15, verbose_name='ساعت')),
                ('city', models.CharField(max_length=40, verbose_name='شهر')),
                ('oprator', models.CharField(max_length=30, verbose_name='اپراتور')),
                ('status', models.CharField(choices=[('Filter', 'Filter'), ('Without Filter', 'Without Filter')], max_length=18, verbose_name='وضعیت')),
                ('filter', models.CharField(choices=[('Drop After Connect', 'Drop After Connect'), ('Drop Pack Filter', 'Drop Pack Filter'), ('Fast And Stable', 'Fast And Stable'), ('Full Filter', 'Full Filter'), ('Low Speed Or UnStable', 'Low Speed Or UnStable')], max_length=38, verbose_name='فیلترینگ')),
                ('server_ip', models.CharField(blank=True, max_length=60, null=True, verbose_name='آیپی سرور')),
                ('server_host', models.CharField(blank=True, max_length=200, null=True, verbose_name='هاست سرور')),
                ('server_isp', models.CharField(blank=True, max_length=100, null=True, verbose_name='ارائه دهنده سرور')),
                ('server_region', models.CharField(blank=True, max_length=150, null=True, verbose_name='منطقه سرور')),
                ('server_city', models.CharField(blank=True, max_length=80, null=True, verbose_name='شهر سرور')),
                ('server_Latitude', models.CharField(blank=True, max_length=200, null=True, verbose_name='عرض جغرافیایی سرور')),
                ('server_Longitude', models.CharField(blank=True, max_length=200, null=True, verbose_name='طول جغرافیایی سرور')),
                ('ping_speed', models.IntegerField(blank=True, null=True, verbose_name='سرعت پینگ')),
                ('ttl', models.IntegerField(blank=True, null=True, verbose_name='حجم بسته')),
                ('proxy_port', models.CharField(blank=True, max_length=7, null=True, verbose_name='پورت پروکسی')),
                ('proxy_secret', models.CharField(blank=True, max_length=200, null=True, verbose_name='رمز پروکسی')),
                ('server_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_country', to='vpn.country', verbose_name='کشور سرور')),
                ('vpn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpns', to='vpn.vpn')),
            ],
            options={
                'verbose_name': 'نتیجه تست',
                'verbose_name_plural': 'نتایج تست ها',
            },
        ),
        migrations.CreateModel(
            name='Isp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='اسم')),
                ('url', models.CharField(blank=True, max_length=30, null=True, verbose_name='آدرس')),
                ('cloud', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=18, null=True, verbose_name='وضعیت')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country', to='vpn.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'ارائه دهنده خدمات',
                'verbose_name_plural': 'ارائه دهندگان خدمات',
            },
        ),
    ]
