# Generated by Django 5.0 on 2024-04-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='name',
            field=models.CharField(verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='platform',
            field=models.CharField(choices=[('Android', 'Android'), ('Telegram', 'Telegram'), ('Windows', 'Windows'), ('Chrome', 'Chrome'), ('Ios', 'Ios')], max_length=10, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='vpn_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='کشور سازنده'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='vpn_maker',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام سازنده'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='vpn_normal_user_fee',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Limited Free', 'Limited Free'), ('Non-free', 'Non-free')], default='', max_length=12, verbose_name='وضعیت رایگان بودن'),
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8, verbose_name='تاریخ')),
                ('time', models.CharField(max_length=8, verbose_name='ساعت')),
                ('city', models.CharField(max_length=30, verbose_name='شهر')),
                ('server_ip', models.CharField(blank=True, default='', verbose_name='آیپی سرور')),
                ('server_host', models.CharField(blank=True, default='', verbose_name='هاست سرور')),
                ('server_isp', models.CharField(blank=True, default='', verbose_name='ارائه دهنده سرور')),
                ('server_country', models.CharField(blank=True, default='', verbose_name='کشور سرور')),
                ('server_region', models.CharField(blank=True, default='', verbose_name='منطقه سرور')),
                ('server_city', models.CharField(blank=True, default='', verbose_name='شهر سرور')),
                ('server_Latitude', models.CharField(blank=True, default='', verbose_name='عرض جغرافیایی سرور')),
                ('server_Longitude', models.CharField(blank=True, default='', verbose_name='طول جغرافیایی سرور')),
                ('ping_speed', models.IntegerField(blank=True, null=True, verbose_name='سرعت پینگ')),
                ('ttl', models.IntegerField(blank=True, default='', verbose_name='حجم بسته')),
                ('proxy_port', models.CharField(blank=True, default='', max_length=7, verbose_name='پورت پروکسی')),
                ('proxy_secret', models.CharField(blank=True, default='', verbose_name='رمز پروکسی')),
                ('vpn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpns', to='vpn.vpn')),
            ],
            options={
                'verbose_name': 'نتیجه تست',
                'verbose_name_plural': 'نتایج تست ها',
            },
        ),
    ]
