# Generated by Django 5.0 on 2024-04-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_alter_vpn_name_alter_vpn_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='filter',
            field=models.CharField(blank=True, choices=[('Drop After Connect', 'Drop After Connect'), ('Drop Pack Filter', 'Drop Pack Filter'), ('Fast And Stable', 'Fast And Stable'), ('Full Filter', 'Full Filter'), ('Low Speed Or UnStable', 'Low Speed Or UnStable')], max_length=38, null=True, verbose_name='فیلترینگ'),
        ),
        migrations.AddField(
            model_name='test',
            name='oprator',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='اپراتور'),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(blank=True, choices=[('Filter', 'Filter'), ('Without Filter', 'Without Filter')], max_length=18, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='test',
            name='proxy_port',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='پورت پروکسی'),
        ),
        migrations.AlterField(
            model_name='test',
            name='proxy_secret',
            field=models.CharField(blank=True, null=True, verbose_name='رمز پروکسی'),
        ),
        migrations.AlterField(
            model_name='test',
            name='server_Latitude',
            field=models.CharField(blank=True, null=True, verbose_name='عرض جغرافیایی سرور'),
        ),
        migrations.AlterField(
            model_name='test',
            name='server_Longitude',
            field=models.CharField(blank=True, null=True, verbose_name='طول جغرافیایی سرور'),
        ),
        migrations.AlterField(
            model_name='test',
            name='server_city',
            field=models.CharField(blank=True, null=True, verbose_name='شهر سرور'),
        ),
        migrations.AlterField(
            model_name='test',
            name='server_country',
            field=models.CharField(blank=True, null=True, verbose_name='کشور سرور'),
        ),
        migrations.AlterField(
            model_name='test',
            name='server_host',
            field=models.CharField(blank=True, null=True, verbose_name='هاست سرور'),
        ),
        migrations.AlterField(
            model_name='test',
            name='server_ip',
            field=models.CharField(blank=True, null=True, verbose_name='آیپی سرور'),
        ),
        migrations.AlterField(
            model_name='test',
            name='server_isp',
            field=models.CharField(blank=True, null=True, verbose_name='ارائه دهنده سرور'),
        ),
        migrations.AlterField(
            model_name='test',
            name='server_region',
            field=models.CharField(blank=True, null=True, verbose_name='منطقه سرور'),
        ),
        migrations.AlterField(
            model_name='test',
            name='ttl',
            field=models.IntegerField(blank=True, null=True, verbose_name='حجم بسته'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='vpn_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور سازنده'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='vpn_maker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سازنده'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='vpn_normal_user_fee',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Limited Free', 'Limited Free'), ('Non-free', 'Non-free')], max_length=12, null=True, verbose_name='وضعیت رایگان بودن'),
        ),
    ]
