# Generated by Django 5.0 on 2024-04-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_test_filter_test_oprator_test_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='filter',
            field=models.CharField(choices=[('Drop After Connect', 'Drop After Connect'), ('Drop Pack Filter', 'Drop Pack Filter'), ('Fast And Stable', 'Fast And Stable'), ('Full Filter', 'Full Filter'), ('Low Speed Or UnStable', 'Low Speed Or UnStable')], max_length=38, verbose_name='فیلترینگ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='oprator',
            field=models.CharField(max_length=30, verbose_name='اپراتور'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('Filter', 'Filter'), ('Without Filter', 'Without Filter')], max_length=18, verbose_name='وضعیت'),
        ),
    ]
