# Generated by Django 5.0 on 2024-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_alter_test_filter_alter_test_oprator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.IntegerField(verbose_name='تاریخ'),
        ),
    ]
