# Generated by Django 5.0 on 2024-05-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_alter_test_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='اسم')),
                ('country_id', models.CharField(max_length=3, verbose_name='آیدی_کشور')),
                ('continent', models.CharField(max_length=13, verbose_name='قاره')),
                ('population', models.CharField(max_length=100, verbose_name='جمعیت')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشور ها',
            },
        ),
    ]
