# Generated by Django 5.0 on 2024-05-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='قاره'),
        ),
        migrations.AddField(
            model_name='country',
            name='persian_name',
            field=models.CharField(blank=True, null=True, verbose_name='اسم فارسی'),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(verbose_name='جمعیت'),
        ),
    ]
