# Generated by Django 5.0 on 2024-05-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0007_country_flag_country_persian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='persian_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='اسم فارسی'),
        ),
    ]
