# Generated by Django 5.0 on 2024-06-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_alter_country_persian_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='server_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_country', to='vpn.country', verbose_name='کشور سرور'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='vpn_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vpn_country', to='vpn.country', verbose_name='کشور سازنده'),
        ),
        migrations.CreateModel(
            name='Isp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='اسم')),
                ('url', models.CharField(blank=True, max_length=30, null=True, verbose_name='آدرس')),
                ('cloud', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=18, null=True, verbose_name='وضعیت')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country', to='vpn.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'ارائه دهنده خدمات',
                'verbose_name_plural': 'ارائه دهندگان خدمات',
            },
        ),
    ]
