# Generated by Django 5.0 on 2024-06-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0009_alter_test_server_country_alter_vpn_vpn_country_isp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='قاره'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='آیدی_کشور'),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='جمعیت'),
        ),
    ]
