# Generated by Django 5.0 on 2024-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0010_alter_country_continent_alter_country_country_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.CharField(max_length=10, verbose_name='ساعت'),
        ),
    ]
