# Generated by Django 5.0 on 2024-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0011_alter_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='city',
            field=models.CharField(verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.CharField(verbose_name='ساعت'),
        ),
    ]
